rly_file = "Croydon.rly"
ttb_files = []
ssn_files = []
country_code = "GB"
name = ""
description = ""
display_name = "Croydon"
author = "Daniel Gill"
contributors = [ "Daniel-Gill",]
graphic_files = []
img_files = [ "Croydon.bmp",]
doc_files = [ "README.md",]
release_date = "2022-01-27"
version = "1.0.0"
